version: '2'
services:
    bcb-app:
        image: bcb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://bcb-postgresql:5432/bcb
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=bcb-elasticsearch:9300
        ports:
            - 8080:8080
    bcb-postgresql:
        extends:
            file: postgresql.yml
            service: bcb-postgresql
    bcb-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: bcb-elasticsearch
